### ISSUE TITLE
Radix sort

### ISSUE THREAD

**Issue by vipuluthaiah** [TheAlgorithms/Dart#147]
how can write the bellow code in dart
//js code
let digitBuckets = Array.from({length: 10}, () => []);
//dart code
List digitBuckets = List.from({});//confused here

//how can i write this: Array.from({length: 10}, () => []);
//in dart List digitBuckets = ??

**Comment by Parowicz** [comment]
Hello
From what i see in js `Array.from` is similar to dart [List.generate](https://api.dart.dev/stable/2.10.4/dart-core/List/List.generate.html)

```dart
var x = List.generate(10, (_) => []);
```

**Comment by vipuluthaiah** [comment]
also i am facing a problem in
js code
`  nums = [].concat(...digitBuckets);`
dart code
`  nums=[].addAll(...digitBucketsd);//facing problem here and confused`
![image](https://user-images.githubusercontent.com/45168922/100494902-5eb3c200-316c-11eb-89a9-c9718ba2c772.png)


how can i do this
`  nums = [].concat(...digitBuckets);` in dart?

**Comment by Parowicz** [comment]
You want to flatten that list? I think closest function would be [List.expand](https://api.dart.dev/stable/2.5.1/dart-core/Iterable/expand.html)

```dart
List<List<int>> digitBuckets = [[1], [1, 2], [3, 10, 15, 100], [4]];

List<int> nums = digitBuckets.expand((lst) => lst).toList();
```

**Comment by vipuluthaiah** [comment]
Thanks a lot!

**Comment by vipuluthaiah** [comment]
Can i add my radix sort to u this repo??

**Comment by Parowicz** [comment]
Yea, we don't have that one yet.
You can make pull request.

**Comment by vipuluthaiah** [comment]
sure!
