### ISSUE TITLE
Alots of deprecated member use

### ISSUE THREAD

**Issue by Djsmk123** [TheAlgorithms/Dart#186]
Some of the algorithm's codes are still using deprecated members for e.g:

```
'List.List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead.
Try replacing the use of the deprecated member with the replacement.

```

I want to fix this.

**Comment by akashgk** [comment]
Closing this issue as it will be fixed with updating the dart to latest.
https://github.com/TheAlgorithms/Dart/issues/176
